eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka
      
  instance:
    hostname: localhost
    prefer-ip-address: true
    
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include:
        - "*"
spring:
  data:
    mongodb:
      host: localhost
      database: test
      port: 27017
      
logging:
  level:
   '[org.springframework.data.mongodb]':  debug        
